In [1]:
# !pip install openpyxl
# !pip install Flask
import sqlite3
import pandas as pd

C:\Users\ramak\AppData\Local\Temp\ipykernel_21716\2353985848.py:4: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_excel("IMDB Top250 Movies.xlsx")

In [3]:
df.head()

,Movies Names,Rating out of 10,Count of Ratings,Release Date,Budget,Domestic Gross,Domestic Gross2,Domestic Weekend Gross,Domestic Weekend,Domestic Weekend Gross Date,Worldwide Gross
0,The Shawshank Redemption,9.3,2.9M,"October 14, 1994 (India)","$25,000,000 (estimated)",US & Canada,$28767189,US & Canada,$727327,Sep 25 1994,"$28,904,642"
1,The Godfather,9.2,2M,1978 (India),"$6,000,000 (estimated)",US & Canada,$136381073,US & Canada,$302393,Mar 19 1972,"$250,342,030"
2,The Dark Knight,9.0,2.9M,"July 18, 2008 (India)","$185,000,000 (estimated)",US & Canada,$534987076,US & Canada,$158411483,Jul 20 2008,"$1,008,486,720"
3,The Godfather: Part II,9.0,1.4M,1979 (India),"$13,000,000 (estimated)",US & Canada,$47834595,US & Canada,$171417,Nov 10 2019,"$47,962,897"
4,12 Angry Men,9.0,861K,"April 10, 1957 (United States)","$350,000 (estimated)",US & Canada,Not Found,US & Canada,Not Found,Not Found,"$2,667"

In [4]:
con = sqlite3.connect("IMDB.db")
cursor = con.cursor()

In [5]:
df.to_sql("Movies", con, if_exists='replace', index=False)

250

In [6]:
cursor.execute("Select * from Movies").fetchall()

[('The Shawshank Redemption',
  '9.3',
  '2.9M',
  'October 14, 1994 (India)',
  '$25,000,000 (estimated)',
  'US & Canada',
  '$28767189',
  'US & Canada',
  '$727327',
  'Sep 25 1994',
  '$28,904,642'),
 ('The Godfather',
  '9.2',
  '2M',
  '1978 (India)',
  '$6,000,000 (estimated)',
  'US & Canada',
  '$136381073',
  'US & Canada',
  '$302393',
  'Mar 19 1972',
  '$250,342,030'),
 ('The Dark Knight',
  '9.0',
  '2.9M',
  'July 18, 2008 (India)',
  '$185,000,000 (estimated)',
  'US & Canada',
  '$534987076',
  'US & Canada',
  '$158411483',
  'Jul 20 2008',
  '$1,008,486,720'),
 ('The Godfather: Part II',
  '9.0',
  '1.4M',
  '1979 (India)',
  '$13,000,000 (estimated)',
  'US & Canada',
  '$47834595',
  'US & Canada',
  '$171417',
  'Nov 10 2019',
  '$47,962,897'),
 ('12 Angry Men',
  '9.0',
  '861K',
  'April 10, 1957 (United States)',
  '$350,000 (estimated)',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$2,667'),
 ("Schindler's List",
  '9.0',
  '1.4M',
  'December 15, 1993 (India)',
  '$22,000,000 (estimated)',
  'US & Canada',
  '$96898818',
  'US & Canada',
  '$656636',
  'Dec 19 1993',
  '$322,161,245'),
 ('The Lord of the Rings: The Return of the King',
  '9.0',
  '2M',
  'February 6, 2004 (India)',
  '$94,000,000 (estimated)',
  'US & Canada',
  '$379427292',
  'US & Canada',
  '$72629713',
  'Dec 21 2003',
  '$1,156,598,523'),
 ('Pulp Fiction',
  '8.9',
  '2.2M',
  'October 14, 1994 (India)',
  '$8,000,000 (estimated)',
  'US & Canada',
  '$107928762',
  'US & Canada',
  '$9311882',
  'Oct 16 1994',
  '$213,928,762'),
 ('The Lord of the Rings: The Fellowship of the Ring',
  '8.9',
  '2M',
  'March 15, 2002 (India)',
  '$93,000,000 (estimated)',
  'US & Canada',
  '$316115420',
  'US & Canada',
  '$47211490',
  'Dec 23 2001',
  '$884,041,698'),
 ('Il Buono, Il Brutto, Il Cattivo',
  '8.8',
  '809K',
  'April 15, 1969 (India)',
  '$1,200,000 (estimated)',
  'US & Canada',
  '$25100000',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$25,259,657'),
 ('Forrest Gump',
  '8.8',
  '2.2M',
  'September 12, 2014 (India)',
  '$55,000,000 (estimated)',
  'US & Canada',
  '$330455270',
  'US & Canada',
  '$24450602',
  'Jul 10 1994',
  '$678,226,465'),
 ('The Lord of the Rings: The Two Towers',
  '8.8',
  '1.8M',
  'March 28, 2003 (India)',
  '$94,000,000 (estimated)',
  'US & Canada',
  '$342952511',
  'US & Canada',
  '$62007528',
  'Dec 22 2002',
  '$948,945,489'),
 ('Fight Club',
  '8.8',
  '2.3M',
  'October 15, 1999 (India)',
  '$63,000,000 (estimated)',
  'US & Canada',
  '$37030102',
  'US & Canada',
  '$11035485',
  'Oct 17 1999',
  '$101,320,107'),
 ('Inception',
  '8.8',
  '2.5M',
  'July 16, 2010 (India)',
  '$160,000,000 (estimated)',
  'US & Canada',
  '$292587330',
  'US & Canada',
  '$62785337',
  'Jul 18 2010',
  '$839,030,630'),
 ('Dune: Part Two',
  '8.8',
  '290K',
  'March 1, 2024 (India)',
  '$190,000,000 (estimated)',
  'US & Canada',
  '$244890027',
  'US & Canada',
  '$82505391',
  'Mar 3 2024',
  '$587,090,027'),
 ('Star Wars: Episode V - The Empire Strikes Back',
  '8.7',
  '1.4M',
  'December 10, 1980 (India)',
  '$18,000,000 (estimated)',
  'US & Canada',
  '$292753960',
  'US & Canada',
  '$4910483',
  'May 25 1980',
  '$538,375,067'),
 ('The Matrix',
  '8.7',
  '2M',
  'May 31, 2020 (India)',
  '$63,000,000 (estimated)',
  'US & Canada',
  '$172076928',
  'US & Canada',
  '$27788331',
  'Apr 4 1999',
  '$467,623,299'),
 ('GoodFellas',
  '8.7',
  '1.3M',
  'July 31, 2019 (India)',
  '$25,000,000 (estimated)',
  'US & Canada',
  '$46909721',
  'US & Canada',
  '$6368901',
  'Sep 23 1990',
  '$47,049,784'),
 ("One Flew Over the Cuckoo's Nest",
  '8.7',
  '1.1M',
  'March 10, 1977 (India)',
  '$3,000,000 (estimated)',
  'US & Canada',
  '$108981275',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$109,114,987'),
 ('Se7en',
  '8.6',
  '1.8M',
  'September 22, 1995 (India)',
  '$33,000,000 (estimated)',
  'US & Canada',
  '$100125643',
  'US & Canada',
  '$13949807',
  'Sep 24 1995',
  '$327,333,559'),
 ('Interstellar',
  '8.7',
  '2.1M',
  'November 7, 2014 (India)',
  '$165,000,000 (estimated)',
  'US & Canada',
  '$188020017',
  'US & Canada',
  '$47510360',
  'Nov 9 2014',
  '$733,202,212'),
 ("It's a Wonderful Life",
  '8.6',
  '498K',
  'January 7, 1947 (United States)',
  '$3,180,000 (estimated)',
  'US & Canada',
  '$1483643',
  'US & Canada',
  '$44000',
  'Dec 20 2020',
  '$9,767,242'),
 ('Shichinin No Samurai',
  '8.6',
  '366K',
  'April 26, 1954 (Japan)',
  '¥125,000,000 (estimated)',
  'US & Canada',
  '$318649',
  'US & Canada',
  '$15942',
  'Jul 28 2002',
  '$346,258'),
 ('The Silence of the Lambs',
  '8.6',
  '1.5M',
  'February 14, 1991 (United States)',
  '$19,000,000 (estimated)',
  'US & Canada',
  '$130742922',
  'US & Canada',
  '$13766814',
  'Feb 18 1991',
  '$272,742,922'),
 ('Saving Private Ryan',
  '8.6',
  '1.5M',
  'March 26, 1999 (India)',
  '$70,000,000 (estimated)',
  'US & Canada',
  '$217049603',
  'US & Canada',
  '$30576104',
  'Jul 26 1998',
  '$482,351,251'),
 ('City of God',
  '8.6',
  '798K',
  'January 18, 2007 (India)',
  'R$3,300,000 (estimated)',
  'US & Canada',
  '$7564459',
  'US & Canada',
  '$88292',
  'Jan 19 2003',
  '$30,680,793'),
 ('Life Is Beautiful',
  '8.6',
  '741K',
  'September 18, 2000 (India)',
  '$20,000,000 (estimated)',
  'US & Canada',
  '$57563264',
  'US & Canada',
  '$118920',
  'Oct 25 1998',
  '$230,099,013'),
 ('The Green Mile',
  '8.6',
  '1.4M',
  'March 16, 2000 (India)',
  '$60,000,000 (estimated)',
  'US & Canada',
  '$136801374',
  'US & Canada',
  '$18017152',
  'Dec 12 1999',
  '$286,801,374'),
 ('Terminator 2: Judgment Day',
  '8.6',
  '1.2M',
  'August 24, 1991 (India)',
  '$102,000,000 (estimated)',
  'US & Canada',
  '$205881154',
  'US & Canada',
  '$31765506',
  'Jul 7 1991',
  '$520,881,154'),
 ('Star Wars: Episode IV - A New Hope',
  '8.6',
  '1.4M',
  'July 1, 1978 (India)',
  '$11,000,000 (estimated)',
  'US & Canada',
  '$460998507',
  'US & Canada',
  '$1554475',
  'May 30 1977',
  '$775,398,007'),
 ('Back to the Future',
  '8.5',
  '1.3M',
  'December 9, 1986 (India)',
  '$19,000,000 (estimated)',
  'US & Canada',
  '$214077472',
  'US & Canada',
  '$11152500',
  'Jul 7 1985',
  '$384,577,472'),
 ('Spirited Away',
  '8.6',
  '845K',
  'March 1, 2020 (India)',
  '$19,000,000 (estimated)',
  'US & Canada',
  '$15205725',
  'US & Canada',
  '$449839',
  'Sep 22 2002',
  '$357,561,772'),
 ('The Pianist',
  '8.5',
  '908K',
  'April 3, 2019 (India)',
  '$35,000,000 (estimated)',
  'US & Canada',
  '$32585488',
  'US & Canada',
  '$111261',
  'Dec 29 2002',
  '$120,093,683'),
 ('Parasite',
  '8.5',
  '951K',
  'January 31, 2020 (India)',
  '$11,400,000 (estimated)',
  'US & Canada',
  '$53369749',
  'US & Canada',
  '$393216',
  'Oct 13 2019',
  '$262,099,264'),
 ('Psycho',
  '8.5',
  '716K',
  'May 24, 2020 (India)',
  '$806,947 (estimated)',
  'US & Canada',
  '$32000000',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$32,060,008'),
 ('Spider-man: Across the Spider-verse',
  '8.6',
  '362K',
  'June 1, 2023 (India)',
  '$150,000,000 (estimated)',
  'US & Canada',
  '$381593754',
  'US & Canada',
  '$120663589',
  'Jun 4 2023',
  '$690,897,910'),
 ('Gladiator',
  '8.5',
  '1.6M',
  'September 1, 2000 (India)',
  '$103,000,000 (estimated)',
  'US & Canada',
  '$187705427',
  'US & Canada',
  '$34819017',
  'May 7 2000',
  '$465,387,186'),
 ('The Lion King',
  '8.5',
  '1.1M',
  'October 29, 1994 (India)',
  '$45,000,000 (estimated)',
  'US & Canada',
  '$422783777',
  'US & Canada',
  '$1586753',
  'Jun 19 1994',
  '$968,750,694'),
 ('Léon',
  '8.5',
  '1.2M',
  'September 23, 1996 (India)',
  'FRF\xa0115,000,000 (estimated)',
  'US & Canada',
  '$19501238',
  'US & Canada',
  '$5306558',
  'Nov 20 1994',
  '$19,570,198'),
 ('The Departed',
  '8.5',
  '1.4M',
  'October 31, 2007 (India)',
  '$90,000,000 (estimated)',
  'US & Canada',
  '$132399394',
  'US & Canada',
  '$26887467',
  'Oct 8 2006',
  '$291,481,358'),
 ('American History X',
  '8.5',
  '1.2M',
  'September 21, 1999 (India)',
  '$20,000,000 (estimated)',
  'US & Canada',
  '$6719864',
  'US & Canada',
  '$156076',
  'Nov 1 1998',
  '$23,875,714'),
 ('Whiplash',
  '8.5',
  '983K',
  'February 20, 2015 (India)',
  '$3,300,000 (estimated)',
  'US & Canada',
  '$13092000',
  'US & Canada',
  '$135388',
  'Oct 12 2014',
  '$49,449,489'),
 ('The Prestige',
  '8.5',
  '1.4M',
  'October 20, 2006 (India)',
  '$40,000,000 (estimated)',
  'US & Canada',
  '$53089891',
  'US & Canada',
  '$14801808',
  'Oct 22 2006',
  '$109,676,311'),
 ('Grave of the Fireflies',
  '8.5',
  '309K',
  'April 16, 1988 (Japan)',
  '$3,700,000 (estimated)',
  'US & Canada',
  '$516962',
  'US & Canada',
  '$158101',
  'Aug 12 2018',
  '$519,421'),
 ('Seppuku',
  '8.6',
  '68K',
  'September 16, 1962 (Japan)',
  'Not Found',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$15,222'),
 ('The Usual Suspects',
  '8.5',
  '1.1M',
  'May 10, 1996 (India)',
  '$6,000,000 (estimated)',
  'US & Canada',
  '$23341568',
  'US & Canada',
  '$645363',
  'Aug 20 1995',
  '$23,341,568'),
 ('Casablanca',
  '8.5',
  '604K',
  'January 23, 1943 (United States)',
  '$950,000 (estimated)',
  'US & Canada',
  '$4219709',
  'US & Canada',
  '$181494',
  'Apr 12 1992',
  '$4,656,207'),
 ('Intouchables',
  '8.5',
  '926K',
  'July 13, 2012 (India)',
  '€9,500,000 (estimated)',
  'US & Canada',
  '$10198820',
  'US & Canada',
  '$103507',
  'May 27 2012',
  '$426,590,315'),
 ('Cinema Paradiso',
  '8.5',
  '282K',
  'November 17, 1988 (Italy)',
  '$5,000,000 (estimated)',
  'US & Canada',
  '$12397210',
  'US & Canada',
  '$16552',
  'Feb 4 1990',
  '$13,020,497'),
 ('Not Found',
  'Not Found',
  None,
  'Not Found',
  'Not Found',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  None),
 ('Rear Window',
  '8.5',
  '521K',
  'September 1, 1954 (United States)',
  '$1,000,000 (estimated)',
  'US & Canada',
  '$36764313',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$37,039,396'),
 ("C'era Una Volta Il West",
  '8.5',
  '348K',
  'September 24, 1969 (India)',
  '$5,000,000 (estimated)',
  'US & Canada',
  '$5321508',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$5,435,312'),
 ('Alien',
  '8.5',
  '947K',
  'December 6, 1979 (India)',
  '$11,000,000 (estimated)',
  'US & Canada',
  '$81900459',
  'US & Canada',
  '$3527881',
  'May 28 1979',
  '$106,285,522'),
 ('City Lights',
  '8.5',
  '195K',
  'March 7, 1931 (United States)',
  '$1,500,000 (estimated)',
  'US & Canada',
  '$19181',
  'US & Canada',
  '$9102',
  'Jul 8 2007',
  '$50,419'),
 ('Apocalypse Now',
  '8.4',
  '708K',
  'August 15, 1979 (United States)',
  '$31,500,000 (estimated)',
  'US & Canada',
  '$96042913',
  'US & Canada',
  '$118558',
  'Aug 19 1979',
  '$104,911,478'),
 ('Django Unchained',
  '8.5',
  '1.7M',
  'March 22, 2013 (India)',
  '$100,000,000 (estimated)',
  'US & Canada',
  '$162805434',
  'US & Canada',
  '$30122888',
  'Dec 30 2012',
  '$426,076,293'),
 ('12th Fail',
  '9.0',
  '107K',
  'October 27, 2023 (India)',
  'Not Found',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$138,288'),
 ('Memento',
  '8.4',
  '1.3M',
  'October 20, 2000 (India)',
  '$9,000,000 (estimated)',
  'US & Canada',
  '$25544867',
  'US & Canada',
  '$235488',
  'Mar 18 2001',
  '$40,047,236'),
 ('WALL·E',
  '8.4',
  '1.2M',
  'August 29, 2008 (India)',
  '$180,000,000 (estimated)',
  'US & Canada',
  '$223808164',
  'US & Canada',
  '$63087526',
  'Jun 29 2008',
  '$521,320,168'),
 ('Raiders of the Lost Ark',
  '8.4',
  '1M',
  'December 10, 1981 (India)',
  '$18,000,000 (estimated)',
  'US & Canada',
  '$248159971',
  'US & Canada',
  '$8305823',
  'Jun 14 1981',
  '$389,925,971'),
 ('Das Leben der Anderen',
  '8.4',
  '409K',
  'March 23, 2006 (Germany)',
  '$2,000,000 (estimated)',
  'US & Canada',
  '$11286112',
  'US & Canada',
  '$223000',
  'Feb 11 2007',
  '$77,357,476'),
 ('Sunset Blvd.',
  '8.4',
  '236K',
  'August 4, 1950 (Turkey)',
  '$1,752,000 (estimated)',
  'US & Canada',
  '$299645',
  'US & Canada',
  '$169067',
  'May 13 2018',
  '$304,474'),
 ('Paths of Glory',
  '8.4',
  '212K',
  'December 25, 1957 (United States)',
  '$935,000 (estimated)',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$5,477'),
 ('Avengers: Infinity War',
  '8.4',
  '1.2M',
  'April 27, 2018 (India)',
  '$321,000,000 (estimated)',
  'US & Canada',
  '$678815482',
  'US & Canada',
  '$257698183',
  'Apr 29 2018',
  '$2,052,415,039'),
 ('Spider-Man: Into the Spider-Verse',
  '8.4',
  '667K',
  'December 14, 2018 (India)',
  '$90,000,000 (estimated)',
  'US & Canada',
  '$190241310',
  'US & Canada',
  '$35363376',
  'Dec 16 2018',
  '$384,298,736'),
 ('The Shining',
  '8.4',
  '1.1M',
  'October 4, 2017 (India)',
  '$19,000,000 (estimated)',
  'US & Canada',
  '$45634352',
  'US & Canada',
  '$622337',
  'May 26 1980',
  '$47,380,008'),
 ('Witness for the Prosecution',
  '8.4',
  '137K',
  'February 6, 1958 (United States)',
  '$3,000,000 (estimated)',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$7,693'),
 ('The Great Dictator',
  '8.4',
  '237K',
  'March 7, 1941 (United States)',
  '$2,000,000 (estimated)',
  'US & Canada',
  'Not Found',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$972,212'),
 ('Alien 2',
  '8.4',
  '760K',
  'July 11, 1987 (India)',
  '$18,500,000 (estimated)',
  'US & Canada',
  '$85160248',
  'US & Canada',
  '$10052042',
  'Jul 20 1986',
  '$131,060,248'),
 ('Inglourious Basterds',
  '8.4',
  '1.6M',
  'October 2, 2009 (India)',
  '$70,000,000 (estimated)',
  'US & Canada',
  '$120540719',
  'US & Canada',
  '$38054676',
  'Aug 23 2009',
  '$321,458,605'),
 ('The Dark Knight Rises',
  '8.4',
  '1.8M',
  'July 20, 2012 (India)',
  '$250,000,000 (estimated)',
  'US & Canada',
  '$448149584',
  'US & Canada',
  '$160887295',
  'Jul 22 2012',
  '$1,085,289,416'),
 ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
  '8.4',
  '517K',
  'January 29, 1964 (United Kingdom)',
  '$1,800,000 (estimated)',
  'US & Canada',
  '$9440272',
  'US & Canada',
  '$11751',
  'Jul 17 1994',
  '$9,529,170'),
 ('American Beauty',
  '8.3',
  '1.2M',
  'April 1, 2020 (India)',
  '$15,000,000 (estimated)',
  'US & Canada',
  '$130096601',
  'US & Canada',
  '$861531',
  'Sep 19 1999',
  '$356,296,601'),
 ('Oldeuboi',
  '8.3',
  '633K',
  'October 4, 2017 (India)',
  '$3,000,000 (estimated)',
  'US & Canada',
  '$2458200',
  'US & Canada',
  '$68957',
  'Mar 27 2005',
  '$17,542,965'),
 ('Coco',
  '8.4',
  '587K',
  'November 24, 2017 (India)',
  '$175,000,000 (estimated)',
  'US & Canada',
  '$210460015',
  'US & Canada',
  '$50802605',
  'Nov 26 2017',
  '$814,337,054'),
 ('Amadeus',
  '8.4',
  '426K',
  'September 19, 1984 (United States)',
  '$18,000,000 (estimated)',
  'US & Canada',
  '$51973029',
  'US & Canada',
  '$505276',
  'Sep 23 1984',
  '$52,068,956'),
 ('Toy Story',
  '8.3',
  '1.1M',
  'November 22, 1995 (United States)',
  '$30,000,000 (estimated)',
  'US & Canada',
  '$223225679',
  'US & Canada',
  '$29140617',
  'Nov 26 1995',
  '$394,436,586'),
 ('Das Boot',
  '8.4',
  '264K',
  'February 17, 1982 (France)',
  'DEM\xa032,000,000 (estimated)',
  'US & Canada',
  '$11487676',
  'US & Canada',
  '$26994',
  'Feb 14 1982',
  '$11,488,778'),
 ('Braveheart',
  '8.3',
  '1.1M',
  'June 22, 1995 (India)',
  '$72,000,000 (estimated)',
  'US & Canada',
  '$75609945',
  'US & Canada',
  '$9938276',
  'May 28 1995',
  '$213,216,216'),
 ('Avengers: Endgame',
  '8.4',
  '1.3M',
  'April 26, 2019 (India)',
  '$356,000,000 (estimated)',
  'US & Canada',
  '$858373000',
  'US & Canada',
  '$357115007',
  'Apr 28 2019',
  '$2,799,439,100'),
 ('Joker',
  '8.4',
  '1.5M',
  'October 2, 2019 (India)',
  '$55,000,000 (estimated)',
  'US & Canada',
  '$335477657',
  'US & Canada',
  '$96202337',
  'Oct 6 2019',
  '$1,078,958,629'),
 ('Mononoke-hime',
  '8.3',
  '432K',
  'March 2, 2020 (India)',
  '¥2,400,000,000 (estimated)',
  'US & Canada',
  '$4845631',
  'US & Canada',
  '$144446',
  'Oct 31 1999',
  '$170,204,201'),
 ('Good Will Hunting',
  '8.3',
  '1.1M',
  'January 9, 1998 (United States)',
  '$10,000,000 (estimated)',
  'US & Canada',
  '$138433435',
  'US & Canada',
  '$272912',
  'Dec 7 1997',
  '$225,933,435'),
 ('Kimi No Na Wa.',
  '8.4',
  '317K',
  'August 26, 2016 (Japan)',
  '¥370,000,000 (estimated)',
  'US & Canada',
  '$5017246',
  'US & Canada',
  '$1813781',
  'Apr 9 2017',
  '$382,238,191'),
 ('Once Upon a Time in America',
  '8.3',
  '376K',
  'June 1, 1984 (United States)',
  '$30,000,000 (estimated)',
  'US & Canada',
  '$5321508',
  'US & Canada',
  '$2412014',
  'Jun 3 1984',
  '$5,475,086'),
 ('Tengoku to Jigoku',
  '8.4',
  '53K',
  'March 1, 1963 (Japan)',
  'Not Found',
  'US & Canada',
  '$46808',
  'US & Canada',
  '$15942',
  'Jul 28 2002',
  '$46,808'),
 ('3 Idiots',
  '8.4',
  '433K',
  'December 25, 2009 (India)',
  '₹550,000,000 (estimated)',
  'US & Canada',
  '$6532874',
  'US & Canada',
  '$1645502',
  'Dec 27 2009',
  '$60,262,836'),
 ("Singin' in the Rain",
  '8.3',
  '260K',
  'April 10, 1952 (United States)',
  '$2,540,800 (estimated)',
  'US & Canada',
  '$1884537',
  'US & Canada',
  '$13643',
  'Nov 10 2002',
  '$2,008,537'),
 ('Capharnaüm',
  '8.4',
  '104K',
  'June 21, 2019 (India)',
  '$4,000,000 (estimated)',
  'US & Canada',
  '$1661096',
  'US & Canada',
  '$24988',
  'Dec 16 2018',
  '$64,417,003'),
 ('Oppenheimer',
  '8.3',
  '700K',
  'July 21, 2023 (India)',
  '$100,000,000 (estimated)',
  'US & Canada',
  '$329862540',
  'US & Canada',
  '$82455420',
  'Jul 23 2023',
  '$960,428,540'),
 ('Requiem for a Dream',
  '8.3',
  '896K',
  'October 4, 2017 (India)',
  '$4,500,000 (estimated)',
  'US & Canada',
  '$3635482',
  'US & Canada',
  '$64770',
  'Oct 8 2000',
  '$7,390,108'),
 ('Idi I Smotri',
  '8.4',
  '96K',
  'September 3, 1985 (Philippines)',
  'Not Found',
  'US & Canada',
  '$71909',
  'US & Canada',
  '$16053',
  'Feb 23 2020',
  '$20,929,648'),
 ('Toy Story 3',
  '8.3',
  '890K',
  'June 25, 2010 (India)',
  '$200,000,000 (estimated)',
  'US & Canada',
  '$415004880',
  'US & Canada',
  '$110307189',
  'Jun 20 2010',
  '$1,067,316,101'),
 ('Star Wars: Episode VI - Return of the Jedi',
  '8.3',
  '1.1M',
  'December 16, 1983 (India)',
  '$32,500,000 (estimated)',
  'US & Canada',
  '$316566101',
  'US & Canada',
  '$23019618',
  'May 29 1983',
  '$475,106,177'),
 ('Eternal Sunshine of the Spotless Mind',
  '8.3',
  '1.1M',
  'December 15, 2019 (India)',
  '$20,000,000 (estimated)',
  'US & Canada',
  '$34400301',
  'US & Canada',
  '$8175198',
  'Mar 21 2004',
  '$73,390,334'),
 ('Jagten',
  '8.3',
  '363K',
  'January 10, 2013 (Denmark)',
  'DKK\xa020,000,000 (estimated)',
  'US & Canada',
  '$613308',
  'US & Canada',
  '$43045',
  'Jul 14 2013',
  '$15,886,373'),
 ('2001: A Space Odyssey',
  '8.3',
  '717K',
  'October 4, 2017 (India)',
  '$12,000,000 (estimated)',
  'US & Canada',
  '$60481243',
  'US & Canada',
  '$202759',
  'May 20 2018',
  '$66,543,782'),
 ('Reservoir Dogs',
  '8.3',
  '1.1M',
  'September 2, 1992 (India)',
  '$1,200,000 (estimated)',
  'US & Canada',
  '$2832029',
  'US & Canada',
  '$147839',
  'Oct 25 1992',
  '$2,930,208'),
 ('Ikiru',
  '8.3',
  '87K',
  'October 9, 1952 (Japan)',
  'Not Found',
  'US & Canada',
  '$60239',
  'US & Canada',
  '$2149',
  'Dec 29 2002',
  '$96,302'),
 ('Lawrence of Arabia',
  '8.3',
  '313K',
  'July 30, 2016 (India)',
  '$15,000,000 (estimated)',
  'US & Canada',
  '$45306425',
  'US & Canada',
  '$20846',
  'Sep 22 2002',
  '$45,744,187'),
 ('The Apartment',
  '8.3',
  '196K',
  'June 29, 1960 (Canada)',
  '$3,000,000 (estimated)',
  'US & Canada',
  '$18600000',
  'US & Canada',
  'Not Found',
  'Not Found',
  '$18,778,738'),
 ('North by Northwest',
  '8.3',

In [7]:
con.commit() 
con.close()